"""
AERON backend entrypoint.

Run with:
    uvicorn app.main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI) once running:
    http://localhost:8000/docs
"""
import logging
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .config import settings
from .database import store
from .routers import health, hospitals, directory, emergency, blood, casualty

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")

app = FastAPI(
    title="AERON API",
    description="AI Emergency Response & Resource Orchestration Network — SIH 2026 prototype backend.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(health.router)
app.include_router(hospitals.router)
app.include_router(directory.router)
app.include_router(emergency.router)
app.include_router(blood.router)
app.include_router(casualty.router)


@app.get("/")
def root():
    return {
        "service": "AERON API",
        "status": "running",
        "data_backend": store.backend_name,
        "docs": "/docs",
    }
